title: Mark's Awesome Website
author: Mark
email: mfeder00@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for Mark's website on Github. 

# social links
twitter_username: federmf # DO NOT include the @ character, or else the build will fail!
github_username:  Marksify # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
